### ISSUE TITLE
AoT error

### ISSUE THREAD

**Issue by kristof01** [SoftwarePioniere/ionic-application-insights#1]
Does this library support AoT compiling?
When I try to build my app with AoT, I get the following error:

"Error during template compile of 'ApplicationInsightsModule' Function expressions are not supported in decorators in 'NgModule' 'NgModule'."

**Comment by Zwoch** [comment]
If i run the command 
`ionic cordova build --aot `
i got no error. Which command you call?

**Comment by Zwoch** [comment]
Could you post me your `ionic info`?

**Comment by kristof01** [comment]
I've used the same command but I get the error described above.

My Ionic info is:

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v9.2.0
    npm        : 5.6.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3 Build version 9E145

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by kristof01** [comment]
I've found the error.
It is because your package is directly dependent on Angular (5.2.1). Angular should be marked as a peerDependency. 

If you take a look at the package.json of MarkPieszak's Angular Application Insights (https://github.com/MarkPieszak/angular-application-insights/blob/master/package.json), you can see that Angular is marked as a peerDependency.

Because of this it it possible to have an Angular version mismatch,
which results in the error above.

**Comment by Zwoch** [comment]
I changed and update the package. Thanks a lot for your feedback!
